// <auto-generated />
using System;
using DataFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IngestionDbContext))]
    [Migration("20251109042233_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataFlow.Core.Domain.Entities.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidationResult")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("IngestionJobs");
                });

            modelBuilder.Entity("DataFlow.Core.Domain.Entities.IngestionJob", b =>
                {
                    b.OwnsOne("DataFlow.Core.Domain.ValueObjects.FileMetadata", "FileMetadata", b1 =>
                        {
                            b1.Property<Guid>("IngestionJobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Checksum")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("UploadedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("IngestionJobId");

                            b1.ToTable("IngestionJobs");

                            b1.WithOwner()
                                .HasForeignKey("IngestionJobId");
                        });

                    b.Navigation("FileMetadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
